version: ~> 1.0
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    bash -c "mvn -DskipTests deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests -f pom-spring-boot.xml deploy --settings .travis-settings.xml";
  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    bash -c "mvn -DskipTests clean install"
    bash -c "mvn -DskipTests -f pom-spring-boot.xml clean install";
  fi
env:
  global:
  - secure: Xyxx1EXQn5MGsiCF8GREAe6hUMWKcgzrOBaA7mRkfSl/vEbFWEnSAqUZo8Zh1/2YJGP8uG7O6VYjCJ8xOykzfp+oKntmAYhEZTZAEVCp9x76jSEZs+BM3uOWaEP+xl/wLGfMzMBOby1ItNHAuxAwxztPKeLu6ijNrXaLxURUiulZN9vbBVinoca35gWMKPtaaEk85Fx7BbnnNo9+f3U2LjQGq8ifXHpsUwgrnc66Rl/x+I4ahuxjDNv5W8Afj7r5Mws8oIO3ubn9KuO7YCqDPsUDnMDj25fP4ZuYL/jFnSboasGvdQbnV/UYW3D9gMUlianu6ck9p1fJ4lR3OruDfQ1ASS9H4+JcBSMshPxrYwzHFPWCHHGnJZPQZsm4auX4bhXu0qWyFZjrSomZnJhGnyto6zwUtXOKSMI43HPOYptP9qCoEzGpOrrQT/tsunqx41CDbqv4KFmVV+wrX75xJY3eI837hKnxKK2P6Hzc8ZQ+nub5UH6xes1V72QD91+ZbE7MGDTf/4VViB655lD7GBcCUCi4GfeiZVsWmahnKjkwFjhVrovJfXJ7tQEcCJ6owxFuKqs89999n6jadkQkSfSYyYdNBEJHdd2pgKtqRgWAsYUkL4JQKIuEdcM3MfkepIfMcCa54ZHnZg0LEC+2Jwyb7SiGaI98fRZGs5YKb4s=
  - secure: OBFx7HRlA9MugzWVFzGMvvib5f2r90bsLVGvVLlrlkZhRKUg0z8in78S5+aRWpBbWM6lhRkZd7T+Bsis/9FEsy8cBqEudFGl/Qc8zwxHqWMBK3gSxdakI0AYUhWv3/piRsk3UC9u9cK9J9w87r5vF0vdDd7n77R8IA8uT3I3zXOdU8vjCxMZMQZ+0II+5FUUQooJ7dnwmJGsRBh0gsEV8YwAOiCW1MHLerKRPqfAx6C0dtNECMe4DzFawry4rHxrqQivRk6ZIOfnWmu/D29r6jqUQjdEvXVogTeumJHatOjQ7XvxkqLWmCeakmATIGXlbvJ6SfSK+4IIN2o/HpHfwxPAeJwgZd+EqfZiez89YEHaEkOiAdaEeajm1VE30/CyNisPQQ58G2BgTlp023cDu/v927YEo0gORGwRLlPGUUz+lyvwyedvXxQVtq1cov5F0XiPWUaHCBUkt2HstVyO6OE1/l11WD3CaHcSqbI1PuL403VrwoPKObdh94qG0TDdns4VCHNaHhpAMpXfVPPu+UgGD571pwlk7jfDi1Vrd9IeI0MBVcOEopkotLZiWsJEDHPSGmdSowg4nj3DJpUSXseoeyjyTQrZPjcQNTfoDjuov1QsSPAWtlYLe+MDLK0hyoVfH5YmXiE54NUbYKRqhJjHMDC/ienAYug7qo0pGQ0=
