version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    bash -c "mvn -DskipTests deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests -f pom-spring-boot.xml deploy --settings .travis-settings.xml";
  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    bash -c "mvn -DskipTests clean install"
    bash -c "mvn -DskipTests -f pom-spring-boot.xml clean install";
  fi
env:
  global:
  - secure: mHHKegY8W+ApyQ0P6Jb28K5RKJYcAo6fQwGO7yFuxDSljgw22t9VsgV27QBkoWpJ9NVQ8czIe2ZNvFYGkAvlq+jtjG4jU+ZTZx50o6zKCRljpAoQbIB4y24WwehyPV9cqv5l7sZJ4DNcmw0uDh4wzsX5DYtPxDnaSSsP9a3ptwNOb2wMVT7TwOZTaXMbGM9KK9X6Wf0Rc/AwwKBdqaGgP1Tg78ZQw08aFwYU9Jv+XfKIvNcBjPiNTg0LPO83eewII95VOrrZaao6nmbcrC9I11WGJiLjJJRg1haUBNj9pp1SpgnhMZ7x5PSp8aZl0U8tTHEXZ0XXwCw9SucXZb6DjW+RZ1Mn4MAsrd8c3ILX/ZLwDfT5RVNret1jXWPWYKidmBWDLHkMXb3W5A4K+k3KO+d6VZhT7GDxienfWtti3gXu9l5HHkGf71sFQCablK3g+MExH4BsBe3jG1bJHNziO6zHpvkUFzVQCD71cruFgqj0RVM3WdPedaO/03QvYZJsfDBkbGJqJOx4FK8+8biTAa3yT+4yc0f3EGlrFN2NYSsdVOSS1Xq5sSd3hk76aKEhboe3o1YOhfmYJXR/FB9jj9ogRYG0xn6Zxic+3oEwVDMXsh02MD4yliBLTThUcHWiyuM/3r25BREHBqpkRBgCYTRQUdY7YFfP7j9p+EHNnZA=
  - secure: bevTGXSAhO3qEEsf/1AvfXLAckmsn9Kg/1thnpVvGmhowcaIi7WqxlaosbprbugL7tGcJpS96FnoGy9C0PD/xWTY+YuTsrDgM3GHiY14c71+0W96bvZhY4Tu8RaNF14Z88rRuom1AEMP5yEnPfkSQnzTquethK8vJRRwkcFWnch7+Q41o45dzHnjelY+R3dnD8BEVshg4KZXWJFDXbHfdpHilNZE55VlbQF8EP7owoC7kC3ZRYkmhhRUDWSVyfHZQA6Pc7cfr7p+0OMBnnFBlrnfQu5Gdb0iYLzisUIrf6Wj+0BDWCXCG9qJmiv7RLfQMl1iT6UXUFlk3IySyfZ/B4r/bBY49EC8FkUf+Fm40ViWML7TKU1XdtRlR5nO3wH9W/d26TrcrwsgRjHbXiVd7F9+UCM8H8BvkJ4tFvSypF73/ziEftBcqkOWioE3T7S07OezlwpvqY74/UZ4+DhjlPmLTrY/zeSTRrIReQFd1BJlS1iuBf2lQdUuBx1MBYovTo3yc7G+lzyY9IzcKye3SktIYTI31jHYXtuqXuUDvkuEIQt8YPWx8tO1QJnQs3S8IS45Z48R6Ha+Wk92WYylyoByUew2sevZw1StrgSrIX8c/uwsZR501sD/eBDdn6S6TNNCgZJHS5FEYfV6Ubzvl2dg7DcA3/5syBBWWM/ExTM=
