version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    bash -c "mvn -DskipTests deploy --settings .travis-settings.xml";
    bash -c "mvn -DskipTests -f pom-spring-boot.xml deploy --settings .travis-settings.xml";
  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    bash -c "mvn -DskipTests clean install"
    bash -c "mvn -DskipTests -f pom-spring-boot.xml clean install";
  fi
env:
  global:
  - secure: mHHKegY8W+ApyQ0P6Jb28K5RKJYcAo6fQwGO7yFuxDSljgw22t9VsgV27QBkoWpJ9NVQ8czIe2ZNvFYGkAvlq+jtjG4jU+ZTZx50o6zKCRljpAoQbIB4y24WwehyPV9cqv5l7sZJ4DNcmw0uDh4wzsX5DYtPxDnaSSsP9a3ptwNOb2wMVT7TwOZTaXMbGM9KK9X6Wf0Rc/AwwKBdqaGgP1Tg78ZQw08aFwYU9Jv+XfKIvNcBjPiNTg0LPO83eewII95VOrrZaao6nmbcrC9I11WGJiLjJJRg1haUBNj9pp1SpgnhMZ7x5PSp8aZl0U8tTHEXZ0XXwCw9SucXZb6DjW+RZ1Mn4MAsrd8c3ILX/ZLwDfT5RVNret1jXWPWYKidmBWDLHkMXb3W5A4K+k3KO+d6VZhT7GDxienfWtti3gXu9l5HHkGf71sFQCablK3g+MExH4BsBe3jG1bJHNziO6zHpvkUFzVQCD71cruFgqj0RVM3WdPedaO/03QvYZJsfDBkbGJqJOx4FK8+8biTAa3yT+4yc0f3EGlrFN2NYSsdVOSS1Xq5sSd3hk76aKEhboe3o1YOhfmYJXR/FB9jj9ogRYG0xn6Zxic+3oEwVDMXsh02MD4yliBLTThUcHWiyuM/3r25BREHBqpkRBgCYTRQUdY7YFfP7j9p+EHNnZA=
  - secure: FwrWAK9mXw+KOdhnn05dhEP4vPSQKw/Pi/E0p7JiLRUIqJtoS+Urhb3z2C4muKUmZJoOB4A1y6ti3DlANZ92GG8BnNPiaCfImBIGB2eI9DW95LjXnzLni1N8pIIeG+/VWY7F6ZqHWBIlG8/Y0toTyCaXZB/psxeXJt4jT8bqSi2y+py2R5bhkeid2YR/yqX0H2OLDGC4h+xSUAWMLWs38WEbon3auG4Z699Orc1333HWULgIyesjZVlyYXJBeZVEUWic1iKWBGO9X/3JAJo8vIZLY6Ay5skn7x/SDEqo5x0I2pBzUUn6CresIgkkd8bVIhFFMrCV2aPqzJUKnvdzlJdfRaK6v77RcdlCSfVMfqJXkzbYoEJmXKny6J1yDrd9qsuZPKCEs+w/U+Fqpuo5XjTq4lCbzuuNdT7wXWM6vpO2aNB9ebEWrJAtiVGGG0sim5iEpL0Mhd9/7k9hLNHKpX+yxdNiwu2sLGQHe8H+iBiceYSMgr2qMn0xsmhT44jf3EhaXog5i/XDD/Z1RkyVycl0ckYrypJkpCtmOLkg6zhPTDEfuVbLu4MEDK+uOVfUcj8dBjt5ky16Jgy1hZQRuRmoJCFOB3abh0lA1tmUtu5mjCfTndAkrOyT1ml4oBi4VkBS5bi4LxkOjuXt0mOCVQxp51YjXHiXunihu8X6K60=
